# Generated by Django 6.1.1 on 2026-10-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_featuredgame_delete_featuredgames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
