# Generated by Django 6.1.1 on 2026-09-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='igdb_id',
            new_name='rawg_id',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='igdb_id',
            new_name='rawg_id',
        ),
    ]
