# Generated by Django 6.1.1 on 2026-10-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_igdb_id_game_rawg_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='first_release_date',
            new_name='release_date',
        ),
    ]
